repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0  # use the latest stable version or pin a specific one
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # pin a stable version
    hooks:
      - id: isort
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: []
        language_version: python3
